version: "3"
services:
  front-app-detection-violent:
    restart: always
    ports:
      - "3000:3000"
    container_name: front-app-detection-violent
    build: .
    command: npm run start
    volumes:
      - .:/app
      - /app/node_modules